spring.application.name=backend

server.port=8080

# PostgreSQL config (environment-based for team safety)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demomanagement_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:2237848$}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false